name = "ghost-game"
main = "src/index.ts"
compatibility_date = "2024-12-02"
compatibility_flags = ["nodejs_compat"]

# 开发服务器配置
[dev]
port = 8788
local_protocol = "http"

[env.production]
vars = { ENVIRONMENT = "production" }

# 飞书应用配置
[vars]
FEISHU_APP_ID = "cli_a90f138b1123dcb1"
FEISHU_APP_SECRET = "wuVKbbDbwdd5OBs96X3cCeGFlfgEICXb"
# 游戏配置
ONLINE_OFFSET = "3600"
BIG_MAP_LENGTH = "400"
BIG_MAP_WIDTH = "400"
VIEW_BIG_MAP_AREA = "9"
DISTANCE_TIME_RATE = "5"
FIXED_MOVE_TIME = "210"
EXPLORE_GOLD = "10"

[[d1_databases]]
binding = "DB"
database_name = "ghost-game-db"
database_id = "dd1e2677-5330-4681-ae87-b915e6631341"

[[routes]]
pattern = "game.free-node.xyz/*"
zone_name = "free-node.xyz"
