/**
 * PopupType - 弹窗类型枚举
 * 
 * 与 PopUp.js 中的 what 值对应
 */
export enum PopupType {
  /** 消息框 */
  MessageBox = 0,
  /** 选择框（确认/取消） */
  Choose = 1,
  /** 取消事件 */
  EventControl = 2,
  /** 删除邮件确认 */
  DeleteMail = 3,
  /** 退出游戏确认 */
  Exit = 4,
  /** 元宝不足提示 */
  NeedGold = 25,
  /** 占领山寨元宝不足 */
  NeedGoldOccupy = 108,
  /** 攻击/征服玩家 */
  AttackPlayer = 29,
  /** 支援城市 */
  SupportCity = 30,
  /** 占领山寨攻击 */
  OccupyMountain = 82,
  /** 攻擂擂台 */
  ArenaList = 105,
  /** 占领山寨列表 */
  OccupyList = 107,
  /** 占领山寨 */
  OccupyMountain2 = 92,
  /** 征服玩家 */
  ConquerPlayer = 110,
  /** 资源交换倍数 */
  ResourceExchange = 106,
  /** 招募弟子 */
  ConscribeChild = 31,
  /** 快速招募弟子 */
  FastConscribeChild = 83,
  /** 自动闭关 */
  AutoExp = 84,
  /** 查看闭关状态 */
  LookAutoExp = 85,
  /** 出售物品 */
  SellEquip = 33,
  /** 使用物品 */
  UseEquip = 37,
  /** 购买物品 */
  BuyEquip = 35,
  /** 出售物品(输入价格) */
  SellEquipInput = 32,
  /** 修复物品 */
  RepairEquip = 42,
  /** 卸下物品 */
  RemoveEquip = 43,
  /** 分解物品 */
  DisassembleEquip = 47,
  /** 节日礼包 */
  FeastEquip = 101,
  /** 发送消息 */
  SendMessage = 34,
  /** 查看消息 */
  ReadMessage = 36,
  /** 选择武将装备 */
  ChoiceHero = 38,
  /** 装备列表 */
  EquipList = 39,
  /** 侠客训练中 */
  HeroEducate = 40,
  /** 选择物品 */
  ChoiceItem = 41,
  /** 放弃任务 */
  AbandonTask = 99,
  /** 召回部队 */
  CallCorpsBack = 104,
  /** 查看在线时间 */
  ShowOnlineTime = 200,
}
